[package]
name = "file-rustler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yml = { version = "0.0" }
shellexpand = { version = "3.1" }
open = { version = "5.3" }
